# Generated by Django 6.0 on 2025-12-28 01:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicephoto',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Service photo', 'verbose_name_plural': 'Service photos'},
        ),
        migrations.RenameField(
            model_name='serviceorder',
            old_name='issue_description',
            new_name='reported_issue',
        ),
        migrations.RemoveField(
            model_name='servicephoto',
            name='created_at',
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='servicephoto',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bike',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='bike',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_orders', to='service.bike'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='status',
            field=models.CharField(choices=[('new', 'Nová'), ('in_progress', 'Prebieha oprava'), ('done', 'Hotová')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Otvorený'), ('waiting_admin', 'Čaká na servis'), ('waiting_customer', 'Čaká na zákazníka'), ('closed', 'Zatvorený')], default='waiting_admin', max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='author_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin')], max_length=20),
        ),
    ]
