# Generated by Django 6.0 on 2025-12-28 01:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_servicephoto_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bike',
            options={'ordering': ['brand', 'model', 'serial_number']},
        ),
        migrations.AlterModelOptions(
            name='customerprofile',
            options={'ordering': ['full_name', 'email']},
        ),
        migrations.AlterModelOptions(
            name='serviceorder',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='servicephoto',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='ticketmessage',
            options={'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='customerprofile',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='serviceorder',
            old_name='reported_issue',
            new_name='issue_description',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='serviceorder',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='servicephoto',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='servicephoto',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bike',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='bike',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='service.bike'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='status',
            field=models.CharField(choices=[('nova', 'Nová'), ('prebieha', 'Prebieha oprava'), ('hotova', 'Hotová')], default='nova', max_length=32),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Otvorený'), ('waiting_admin', 'Čaká na servis'), ('waiting_customer', 'Čaká na zákazníka'), ('closed', 'Zatvorený')], default='open', max_length=32),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='role',
            field=models.CharField(choices=[('customer', 'Zákazník'), ('admin', 'Servis')], default='customer', max_length=20),
        ),
    ]
