# Generated by Django 6.0 on 2025-12-28 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_bike_options_alter_customerprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmessage',
            name='role',
            field=models.CharField(choices=[('customer', 'Zákazník'), ('admin', 'Servis'), ('system', 'Systém')], default='customer', max_length=20),
        ),
    ]
