# Generated by Django 6.0 on 2025-12-29 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_ticketmessage_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='service_code',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=5, null=True, unique=True),
        ),
    ]
