# Generated by Django 5.2.9 on 2026-01-01 23:30

import django.db.models.deletion
import service.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_serviceorder_service_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bike',
            options={},
        ),
        migrations.AlterModelOptions(
            name='customerprofile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='serviceorder',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ticketmessage',
            options={},
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='customer',
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='checklist',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='promised_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='bike',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bike',
            name='model',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='bike',
            name='serial_number',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='bike',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_orders', to='service.bike'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='service_code',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='status',
            field=models.CharField(choices=[('NEW', 'Nová'), ('IN_PROGRESS', 'V procese'), ('WAITING_PART', 'Čakáme na diel'), ('READY', 'Pripravené'), ('DONE', 'Hotová')], default='NEW', max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Otvorený'), ('WAITING_ADMIN', 'Čaká na servis'), ('WAITING_CUSTOMER', 'Čaká na zákazníka'), ('CLOSED', 'Zatvorený')], default='OPEN', max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Zákazník'), ('ADMIN', 'Servis')], default='CUSTOMER', max_length=20),
        ),
        migrations.CreateModel(
            name='ServiceOrderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('SMS', 'SMS'), ('EMAIL_PROTOCOL', 'Email protokol'), ('EMAIL_DONE', 'Email hotová')], max_length=40)),
                ('body', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_logs', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='service.serviceorder')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceOrderPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=service.models.service_photo_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='service.serviceorder')),
            ],
        ),
        migrations.DeleteModel(
            name='ServicePhoto',
        ),
    ]
