# Generated by Django 5.2.9 on 2026-01-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_schema_repair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorderlog',
            name='kind',
            field=models.CharField(choices=[('SMS', 'SMS'), ('EMAIL_INVITE', 'Email pozvánka'), ('EMAIL_PROTOCOL', 'Email protokol'), ('EMAIL_DONE', 'Email hotová')], max_length=40),
        ),
    ]
