# Generated by Django 5.2.9 on 2026-02-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_alter_serviceorderlog_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='completed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='promised_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='status',
            field=models.CharField(choices=[('NEW', 'Nová'), ('IN_PROGRESS', 'V procese'), ('WAITING_PART', 'Čakáme na diel'), ('READY', 'Pripravené'), ('DONE', 'Hotová')], db_index=True, default='NEW', max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Otvorený'), ('WAITING_ADMIN', 'Čaká na servis'), ('WAITING_CUSTOMER', 'Čaká na zákazníka'), ('CLOSED', 'Zatvorený')], db_index=True, default='OPEN', max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='serviceorder',
            index=models.Index(fields=['status', 'completed_at'], name='service_ser_status_e77354_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceorder',
            index=models.Index(fields=['status', 'promised_date'], name='service_ser_status_cd1371_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', 'updated_at'], name='service_tic_status_bca694_idx'),
        ),
    ]
